### ISSUE TITLE
Error: Server responded with 403

### ISSUE THREAD

**Issue by skibop** [DevSnowflake/canvacord#104]
**Describe the bug**

**To Reproduce**
1. Simply just make a rankcard using discord.js
2. Try to send it, you may find that it will work the first time (atleast it did for me), then it will not work after say maybe one hour.

**Expected behavior**

**Please complete the following information:**
 - Node Version: [16.4.0]
 - Library Version: [5.2.3]

**Additional context**
Was working fine before, then had issues.

**Comment by LHCLYT** [comment]
As far as I know it's a Discord bug, they are blocking all attempts to download images without a user-agent, they say they will say something about it in a while.

**Comment by skibop** [comment]
Very well, I'll be on the lookout for anything related to that.

**Comment by techlewi** [comment]
im having same issue

**Comment by DevAndromeda** [comment]
Errors like `Server responded with 403` are caused due to the url you have provided. This happens when you try loading an image via url and the server serving images on that url blocks the request. To successfully load the image, your image server must return status code 200. Possible fix for this:
- use different url
- use the image from your disk
