### ISSUE TITLE
Offset position

### ISSUE THREAD

**Issue by rapsavage1** [DevSnowflake/canvacord#39]
![image0](https://user-images.githubusercontent.com/31476792/95406466-b3a72a80-08d7-11eb-944b-75cee1d31826.png)

The text is being displayed over the number

**Comment by ZKillou** [comment]
Hi !
I have a similar problem, there is a big space between "Rang" and "1" and this space isn't here between "Niveau" and "30"

![rank-2](https://user-images.githubusercontent.com/55600416/97707277-5ad24880-1ab7-11eb-8d03-2268da85cc42.png)

I don't know what can I do because in v4, this problem isn't here.

**Comment by ZKillou** [comment]
Ok I think I have found the problem. When you get the width of the number, you get the width of the entire number but not the width of the number really write (`Util.toAbbrev(parseInt(this.data.rank.data))`)

**Comment by Snowflake107** [comment]
Thanks 👍🏻

**Comment by Snowflake107** [comment]
Should work in latest version
