### ISSUE TITLE
shit not working

### ISSUE THREAD

**Issue by lambdagit101** [DevSnowflake/canvacord#47]
so i tried using canvacord and it did not work
i got banned from the discord server by the shit owner i don't fucking care if you see this snowflake
for "stfu" when i just tried to get my problem solved
10/10 support would never ask again
not my fault your library is not working
anyways fix your library dumbass

**Comment by Scythe108** [comment]
Hm, actually the backage is fully functional. You might wanna chill your attitude, not our fault you became sassy & plain out rude. Don't go trashing packages because you don't know how to be chill and get support properly. You will not be unbanned and it's become obvious you are too young to even be on discord.

**Comment by lambdagit101** [comment]
> Hm, actually the backage is fully functional. You might wanna chill your attitude, not our fault you became sassy & plain out rude. Don't go trashing packages because you don't know how to be chill and get support properly. You will not be unbanned and it's become obvious you are too young to even be on discord.

LMAOOOOOOOOOOOOOOO
